[package]
cairo-version = "=2.8.4"
name = "engine"
version = "1.0.9"
edition = "2023_11"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"                      # scarb run migrate
spawn = "sozo execute dojo_starter-actions spawn --wait"    # scarb run spawn
move = "sozo execute dojo_starter-actions move -c 1 --wait" # scarb run move

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.9" }
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib" }


[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.9" }
