name: Contracts CI
on:
   push:
       branches: ["main"]
   pull_request:
       branches: ["main"]
jobs:
   build-and-test:
       runs-on: ubuntu-latest
       steps:
           - name: Install Rust
             uses: actions-rs/toolchain@v1
             with:
                 toolchain: stable
                 override: true
                 
           - name: Install asdf
             uses: asdf-vm/actions/setup@v3
           
           - name: Checkout code
             uses: actions/checkout@v3

           - name: Install plugins
             run: |
                asdf plugin add scarb
                asdf install scarb latest
                asdf install scarb 2.8.4
                asdf global scarb latest
                asdf plugin add dojo https://github.com/dojoengine/asdf-dojo
                asdf install dojo latest 
                asdf global dojo latest
                asdf plugin add starknet-foundry
                asdf install starknet-foundry latest
                asdf install starknet-foundry 0.33.0
                asdf global starknet-foundry latest
           
           - name: Build contracts
             run: |
                 cd engine
                 sozo build
           
           - name: Run tests
             run: |
                 cd engine
                 sozo test
           
           - name: Check formatting
             run: |
                cd engine
                scarb fmt --check

           - name: ERC20
             run: |
                cd erc/erc20
                scarb build
                scarb test
                scarb fmt --check

           - name: ERC721
             run: |
                cd erc/erc721
                asdf global scarb 2.8.4
                asdf global starknet-foundry 0.33.0
                scarb build
                scarb test
                scarb fmt --check
